networks:
  my_network:
    driver: bridge

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SPARQL_ENDPOINT=http://graphdb:7200/repositories/travelogger
      - DEFAULT_LIMIT=10
      - DEFAULT_RESTAURANT_WAITTIME=1.2 #hours
      - TIME_BUFFER=2 #2 min time buffer
      - DEFAULT_DESINATION_WAITTIME=3
      - USERNAME=aladeen
      - PASSORD=VeryNice
    
    networks:
      - my_network

    env_file:
      - ./.env   

  graphdb:
    image: ontotext/graphdb:10.6.4
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx2048m
    networks:
      - my_network  

volumes:
  graphdb-data:
